model_path: "C:/School/Fall2025/project/runs-20251130T043758Z-1-001/runs/segment/train14/weights/best.onnx"
device: "gpu"   # either "cpu" or "gpu"
output_dir: "./results_python" # optional; where inference results are written (will be created)
conf_threshold: 0.25  # confidence threshold for detections
iou_threshold: 0.45   # IOU threshold for NMS

# Drag race configuration
input_folder: "C:/School/Fall2025/project/data-20251130T043738Z-1-001/data/opg/test/images"
num_copies: 30  # number of copies to make of each image
num_threads: 12   # number of threads to use (optional, omit to use default)